### ISSUE TITLE
Make hearing distance configurable

### ISSUE THREAD

**Issue by DodoEstinto** [n33kos/AlwaysHearActiveWalkie#2]
As said in the title, it would cool have a config file where you can lower the hearing distance.

**Comment by MasterEvilAce** [comment]
+1. default of 20 meters is way too far and it becomes an intercom system instead of walkie talkies. Kind of cheatery. I just want to be able to hear someone else receiving audio over walkie, or hear walkie while it's laying on the table in the ship. 3 meters is plenty for that.

**Comment by n33kos** [comment]
@DodoEstinto
Thanks for the suggestion and PR. I tried to balance it to match the unobstructed spatial audio distance but it makes sense for this value to be configurable.

Sorry for the delay, I wasn't expecting any activity on this repository and missed all of this. After this was posted I believe I released version 1.4.3 I'll follow up on your PR to coordinate getting it rebased on the new version and merged in

**Comment by n33kos** [comment]
Resolved in version 1.4.4
