### ISSUE TITLE
[bug] Clients can hear a transmitters voice from the transmitters Walkie

### ISSUE THREAD

**Issue by Fummowo** [n33kos/AlwaysHearActiveWalkie#4]
Sorry if the title is confusing,
what i'm trying to explain is that when the client is outside the range of speech but inside the range that active walkies can be heard, a player transmitting into a walkie can be heard from that same walkie, basically extending their range to communicate to the range of this mod. without anyone else requiting walkies.
A minor issue, but it takes away from the realism factor.

**Comment by etrant** [comment]
I believe this is solved by #7 as well... You'd need to play with the ranges (The vanilla transmission range is '6' IIRC) 

Someone please correct me if I'm wrong.

**Comment by Fummowo** [comment]
@wheatwarrior Could you explain what each of the values do? or if you have an existing config that works nicely :)

**Comment by etrant** [comment]
> @wheatwarrior Could you explain what each of the values do? or if you have an existing config that works nicely :)

Audible range - How close to the walkie talkie you need to be for it to be heard.

The other two values Im unclear on. 

My group plays on: 

Audible 6
Recording 20
PlayerToPlayerSpatialRange 20

**Comment by n33kos** [comment]
Yes this would also be corrected by configurable audio distances. Sorry I didn't seem to balance this well enough the first time around.

**Comment by n33kos** [comment]
Resolved in version 1.4.4
